// <auto-generated />
namespace What2Eat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class najnowszaKoziu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(najnowszaKoziu));
        
        string IMigrationMetadata.Id
        {
            get { return "201505060003551_najnowszaKoziu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
